server:
  port: 80

fruit:
  list:
    - name: banana
      color: yellow
    - name: apple
      color: red


#property:
#  test:
#    name: property depth test
#
#propertyTest: test
#
#propertyTestList: a,b,c

